module.exports = {
    Apiaceae: "Celery",
    Apocynaceae: "Periwinkle",
    Asteraceae: "Daisy",
    Bignoniaceae: "Bignonia",
    Boraginaceae: "Forget-me-Not",
    Brassicaceae: "Cabbage",
    Caesalpiniaceae: "Bean",
    Campanulaceae: "Bellflower",
    Caryophyllaceae: "Pink",
    Clusiaceaee: "St-Johns-Wort",
    Convolvulaceae: "Bindweed",
    Ericaceae: "Heath",
    Geraniaceae: "Geranium",
    Gesneriaceae: "African-Violet",
    Iridaceae: "Iris",
    Lamiaceae: "Nettle",
    Liliaceae: "Lily",
    Malvaceae: "Mallow",
    Musaceae: "Banana",
    Papaveraceae: "Poppy",
    Ranunculaceae: "Buttercup",
    Rosaceae: "Rose",
    Scrophulariaceae: "Foxglove",
    Solanaceae: "Potato",
    Violaceae: "Violet",
};
